# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsrc/msg.proto\x12\tprotoblog\")\n\x06\x44\x61ta3d\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"Y\n\x08Position\x12\x10\n\x08sensorId\x18\x01 \x02(\x04\x12\x16\n\x0etimestamp_usec\x18\x02 \x02(\x04\x12#\n\x08position\x18\x03 \x02(\x0b\x32\x11.protoblog.Data3d')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATA3D']._serialized_start=28
  _globals['_DATA3D']._serialized_end=69
  _globals['_POSITION']._serialized_start=71
  _globals['_POSITION']._serialized_end=160
# @@protoc_insertion_point(module_scope)
